spring:
  profiles:
    active: dev

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      repositories:
        enabled: true

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration: ${JWT_EXPIRATION}
    refresh-token:
      expiration: ${JWT_REFRESH_EXPIRATION}

worklog:
  cors:
    allowed-origins:
      - http://localhost:3000
  cookies:
    secure: false
    same-site: Strict
    access-name: worklog_access
    refresh-name: worklog_refresh
    refresh-path: /worklog/auth