spring:
  profiles:
    active: dev

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      repositories:
        enabled: true

worklog:
  cors:
    allowed-origins:
      - http://localhost:3000