spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/worklog_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true

  flyway:
    enabled: true

worklog:
  cookies:
    secure: false