ALTER TABLE users
ADD COLUMN isEnabled BOOLEAN DEFAULT TRUE NOT NULL;

ALTER TABLE clients
ADD COLUMN isEnabled BOOLEAN DEFAULT TRUE NOT NULL;

ALTER TABLE tickets
ADD COLUMN isEnabled BOOLEAN DEFAULT TRUE NOT NULL;